.open ./Skat/skat.sqlite

DROP TABLE IF EXISTS SkatUser;
CREATE TABLE [SkatUser](
    [Id] INTEGER  PRIMARY KEY AUTOINCREMENT,
    [UserId] INTEGER NOT NULL,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [IsActive] INTEGER DEFAULT 0
);

DROP TABLE IF EXISTS SkatYear;
CREATE TABLE [SkatYear](
    [Id] INTEGER  PRIMARY KEY AUTOINCREMENT,
    [Label] TEXT,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [ModifiedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [StartDate] TEXT DEFAULT CURRENT_TIMESTAMP,
    [EndDate] TEXT DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS SkatUserYear;
CREATE TABLE [SkatUserYear](
    [Id] INTEGER  PRIMARY KEY AUTOINCREMENT,
    [SkatUserId] INTEGER NOT NULL,
    [SkatYearId] INTEGER NOT NULL,
    [UserId] INTEGER NOT NULL,
    [IsPaid] INTEGER DEFAULT 0,
    [Amount] INTEGER DEFAULT 0,
    FOREIGN KEY ([SkatUserId]) REFERENCES [SkatUser](Id),
    FOREIGN KEY ([SkatYearId]) REFERENCES [SkatYear](Id) ON DELETE CASCADE
);

.open ./Bank/bank.sqlite
DROP TABLE IF EXISTS BankUser;
CREATE TABLE [BankUser](
    [Id] INTEGER  PRIMARY KEY AUTOINCREMENT,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [ModifiedAt] TEXT DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Account;
CREATE TABLE [Account](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [AccountNo] INTEGER NOT NULL,
    [IsStudent] INTEGER DEFAULT 0,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [ModifiedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [InterestRate] INTEGER DEFAULT 0,
    [Amount] INTEGER DEFAULT 0
);

ALTER TABLE [BankUser] ADD COLUMN [UserId] INTEGER REFERENCES [Account](Id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE [Account] ADD COLUMN [BankUserId] INTEGER REFERENCES [BankUser](Id) DEFERRABLE INITIALLY DEFERRED;

DROP TABLE IF EXISTS Deposit;
CREATE TABLE [Deposit](
    [Id] INTEGER  PRIMARY KEY AUTOINCREMENT,
    [BankUserId] INTEGER NOT NULL,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [Amount] INTEGER DEFAULT 0,
    FOREIGN KEY (BankUserId) REFERENCES [BankUser](Id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS Loan;
CREATE TABLE [Loan](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [BankUserId] INTEGER NOT NULL,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [ModifiedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [Amount] INTEGER DEFAULT 0,
    FOREIGN KEY (BankUserId) REFERENCES [BankUser](Id) ON DELETE CASCADE
);

.open ./Borger/borger.sqlite
DROP TABLE IF EXISTS user;
CREATE TABLE [user](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [UserId] INTEGER NOT NULL,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS address;
CREATE TABLE [address] (
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [BorgerUserId] INTEGER NOT NULL,
    [Address] TEXT,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [IsValid] INTEGER DEFAULT 1,
    FOREIGN KEY ([BorgerUserId]) REFERENCES [user](Id) ON DELETE CASCADE
);