CREATE TABLE [BankUser](
    [Id] INTEGER  PRIMARY KEY AUTOINCREMENT,
    [UserId] INTEGER NOT NULL,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [ModifiedAt] TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE [Account](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [BankUserId] INTEGER NOT NULL,
    [AccountNo] INTEGER NOT NULL,
    [IsStudent] INTEGER DEFAULT 0,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [ModifiedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [InterestRate] INTEGER DEFAULT 0,
    [Amount] INTEGER DEFAULT 0,
    FOREIGN KEY (BankUserId) REFERENCES [BankUser](Id) ON DELETE CASCADE    
);

CREATE TABLE [Deposit](
    [Id] INTEGER  PRIMARY KEY AUTOINCREMENT,
    [BankUserId] INTEGER NOT NULL,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [Amount] INTEGER DEFAULT 0,
    FOREIGN KEY (BankUserId) REFERENCES [BankUser](Id) ON DELETE CASCADE
);

CREATE TABLE [Loan](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [BankUserId] INTEGER NOT NULL,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [ModifiedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [Amount] INTEGER DEFAULT 0,
    FOREIGN KEY (BankUserId) REFERENCES [BankUser](Id) ON DELETE CASCADE
);