CREATE TABLE [BankUser](
    [Id] INTEGER  PRIMARY KEY AUTOINCREMENT,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [ModifiedAt] TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE [Account](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [AccountNo] INTEGER NOT NULL,
    [IsStudent] INTEGER DEFAULT 0,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [ModifiedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [InterestRate] INTEGER DEFAULT 0,
    [Amount] INTEGER DEFAULT 0
);

ALTER TABLE [BankUser] ADD COLUMN [UserId] INTEGER REFERENCES [Account](Id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE [Account] ADD COLUMN [BankUserId] INTEGER REFERENCES [BankUser](Id) DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE [Deposit](
    [Id] INTEGER  PRIMARY KEY AUTOINCREMENT,
    [BankUserId] INTEGER NOT NULL,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [Amount] INTEGER DEFAULT 0,
    FOREIGN KEY (BankUserId) REFERENCES [BankUser](Id) ON DELETE CASCADE
);

CREATE TABLE [Loan](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [BankUserId] INTEGER NOT NULL,
    [CreatedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [ModifiedAt] TEXT DEFAULT CURRENT_TIMESTAMP,
    [Amount] INTEGER DEFAULT 0,
    FOREIGN KEY (BankUserId) REFERENCES [BankUser](Id) ON DELETE CASCADE
);