

CREATE TABLE [user](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [UserId] INTEGER NOT NULL,
    [CreatedAt] DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE [address] (
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [BorgerUserId] INTEGER NOT NULL,
    [CreatedAt] DATETIME DEFAULT CURRENT_TIMESTAMP,
    [IsValid] INTEGER DEFAULT 1,
    FOREIGN KEY ([BorgerUserId]) REFERENCES [user](UserId) ON DELETE CASCADE
);